name: IPA Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.8
  FLUTTER_VERSION: 3.27.3

# defaults:
#   run:
#     working-directory: ./app
  
jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet-cli --upgrade

      - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Flet Build IPA
        run: |
          flutter config --no-analytics
          flet build ipa --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION

      - name: Prepare IPA Artifact
        run: |
          cd build/ipa/Runner.xcarchive/Products
          mv Applications Payload
          zip -r app.zip Payload
          mv app.zip app.ipa

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: ipa-build-artifact
          path: build/ipa/Runner.xcarchive/Products/app.ipa
          if-no-files-found: error
          overwrite: false
